/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R500RouteImport } from './routes/500'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AddressesRouteImport } from './routes/addresses'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BecomeDeliveryRouteImport } from './routes/become-delivery'
import { Route as BecomeVendorRouteImport } from './routes/become-vendor'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as OrderSuccessRouteImport } from './routes/order-success'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StreetVendorsRouteImport } from './routes/street-vendors'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VendorRouteImport } from './routes/vendor'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as DeliveryLoginRouteImport } from './routes/delivery.login'
import { Route as OrdersTrackRouteImport } from './routes/orders.track'
import { Route as ProductsProductIdRouteImport } from './routes/products.$productId'
import { Route as VendorLoginRouteImport } from './routes/vendor.login'
import { Route as VendorRoamingRouteImport } from './routes/vendor.roaming'
import { Route as VendorsIndexRouteImport } from './routes/vendors.index'
import { Route as VendorsVendorIdRouteImport } from './routes/vendors.$vendorId'
import { Route as OrdersOrderIdTrackRouteImport } from './routes/orders.$orderId.track'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R500Route = R500RouteImport.update({
  id: '/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AddressesRoute = AddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeDeliveryRoute = BecomeDeliveryRouteImport.update({
  id: '/become-delivery',
  path: '/become-delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeVendorRoute = BecomeVendorRouteImport.update({
  id: '/become-vendor',
  path: '/become-vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSuccessRoute = OrderSuccessRouteImport.update({
  id: '/order-success',
  path: '/order-success',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StreetVendorsRoute = StreetVendorsRouteImport.update({
  id: '/street-vendors',
  path: '/street-vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorRoute = VendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryLoginRoute = DeliveryLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => DeliveryRoute,
} as any)
const OrdersTrackRoute = OrdersTrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => OrdersRoute,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorLoginRoute = VendorLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => VendorRoute,
} as any)
const VendorRoamingRoute = VendorRoamingRouteImport.update({
  id: '/roaming',
  path: '/roaming',
  getParentRoute: () => VendorRoute,
} as any)
const VendorsIndexRoute = VendorsIndexRouteImport.update({
  id: '/vendors/',
  path: '/vendors/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsVendorIdRoute = VendorsVendorIdRouteImport.update({
  id: '/vendors/$vendorId',
  path: '/vendors/$vendorId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdTrackRoute = OrdersOrderIdTrackRouteImport.update({
  id: '/$orderId/track',
  path: '/$orderId/track',
  getParentRoute: () => OrdersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/500': typeof R500Route
  '/about': typeof AboutRoute
  '/addresses': typeof AddressesRoute
  '/admin': typeof AdminRouteWithChildren
  '/become-delivery': typeof BecomeDeliveryRoute
  '/become-vendor': typeof BecomeVendorRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/delivery': typeof DeliveryRouteWithChildren
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/offline': typeof OfflineRoute
  '/order-success': typeof OrderSuccessRoute
  '/orders': typeof OrdersRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/street-vendors': typeof StreetVendorsRoute
  '/terms': typeof TermsRoute
  '/vendor': typeof VendorRouteWithChildren
  '/wishlist': typeof WishlistRoute
  '/admin/login': typeof AdminLoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/delivery/login': typeof DeliveryLoginRoute
  '/orders/track': typeof OrdersTrackRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/vendor/login': typeof VendorLoginRoute
  '/vendor/roaming': typeof VendorRoamingRoute
  '/vendors/$vendorId': typeof VendorsVendorIdRoute
  '/vendors/': typeof VendorsIndexRoute
  '/orders/$orderId/track': typeof OrdersOrderIdTrackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/500': typeof R500Route
  '/about': typeof AboutRoute
  '/addresses': typeof AddressesRoute
  '/admin': typeof AdminRouteWithChildren
  '/become-delivery': typeof BecomeDeliveryRoute
  '/become-vendor': typeof BecomeVendorRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/delivery': typeof DeliveryRouteWithChildren
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/offline': typeof OfflineRoute
  '/order-success': typeof OrderSuccessRoute
  '/orders': typeof OrdersRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/street-vendors': typeof StreetVendorsRoute
  '/terms': typeof TermsRoute
  '/vendor': typeof VendorRouteWithChildren
  '/wishlist': typeof WishlistRoute
  '/admin/login': typeof AdminLoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/delivery/login': typeof DeliveryLoginRoute
  '/orders/track': typeof OrdersTrackRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/vendor/login': typeof VendorLoginRoute
  '/vendor/roaming': typeof VendorRoamingRoute
  '/vendors/$vendorId': typeof VendorsVendorIdRoute
  '/vendors': typeof VendorsIndexRoute
  '/orders/$orderId/track': typeof OrdersOrderIdTrackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/500': typeof R500Route
  '/about': typeof AboutRoute
  '/addresses': typeof AddressesRoute
  '/admin': typeof AdminRouteWithChildren
  '/become-delivery': typeof BecomeDeliveryRoute
  '/become-vendor': typeof BecomeVendorRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/delivery': typeof DeliveryRouteWithChildren
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/offline': typeof OfflineRoute
  '/order-success': typeof OrderSuccessRoute
  '/orders': typeof OrdersRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/street-vendors': typeof StreetVendorsRoute
  '/terms': typeof TermsRoute
  '/vendor': typeof VendorRouteWithChildren
  '/wishlist': typeof WishlistRoute
  '/admin/login': typeof AdminLoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/delivery/login': typeof DeliveryLoginRoute
  '/orders/track': typeof OrdersTrackRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/vendor/login': typeof VendorLoginRoute
  '/vendor/roaming': typeof VendorRoamingRoute
  '/vendors/$vendorId': typeof VendorsVendorIdRoute
  '/vendors/': typeof VendorsIndexRoute
  '/orders/$orderId/track': typeof OrdersOrderIdTrackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/500'
    | '/about'
    | '/addresses'
    | '/admin'
    | '/become-delivery'
    | '/become-vendor'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/delivery'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/notifications'
    | '/offline'
    | '/order-success'
    | '/orders'
    | '/privacy'
    | '/profile'
    | '/refund-policy'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/street-vendors'
    | '/terms'
    | '/vendor'
    | '/wishlist'
    | '/admin/login'
    | '/auth/callback'
    | '/delivery/login'
    | '/orders/track'
    | '/products/$productId'
    | '/vendor/login'
    | '/vendor/roaming'
    | '/vendors/$vendorId'
    | '/vendors/'
    | '/orders/$orderId/track'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/500'
    | '/about'
    | '/addresses'
    | '/admin'
    | '/become-delivery'
    | '/become-vendor'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/delivery'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/notifications'
    | '/offline'
    | '/order-success'
    | '/orders'
    | '/privacy'
    | '/profile'
    | '/refund-policy'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/street-vendors'
    | '/terms'
    | '/vendor'
    | '/wishlist'
    | '/admin/login'
    | '/auth/callback'
    | '/delivery/login'
    | '/orders/track'
    | '/products/$productId'
    | '/vendor/login'
    | '/vendor/roaming'
    | '/vendors/$vendorId'
    | '/vendors'
    | '/orders/$orderId/track'
  id:
    | '__root__'
    | '/'
    | '/500'
    | '/about'
    | '/addresses'
    | '/admin'
    | '/become-delivery'
    | '/become-vendor'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/delivery'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/notifications'
    | '/offline'
    | '/order-success'
    | '/orders'
    | '/privacy'
    | '/profile'
    | '/refund-policy'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/street-vendors'
    | '/terms'
    | '/vendor'
    | '/wishlist'
    | '/admin/login'
    | '/auth/callback'
    | '/delivery/login'
    | '/orders/track'
    | '/products/$productId'
    | '/vendor/login'
    | '/vendor/roaming'
    | '/vendors/$vendorId'
    | '/vendors/'
    | '/orders/$orderId/track'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R500Route: typeof R500Route
  AboutRoute: typeof AboutRoute
  AddressesRoute: typeof AddressesRoute
  AdminRoute: typeof AdminRouteWithChildren
  BecomeDeliveryRoute: typeof BecomeDeliveryRoute
  BecomeVendorRoute: typeof BecomeVendorRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  DeliveryRoute: typeof DeliveryRouteWithChildren
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  OfflineRoute: typeof OfflineRoute
  OrderSuccessRoute: typeof OrderSuccessRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SignupRoute: typeof SignupRoute
  StreetVendorsRoute: typeof StreetVendorsRoute
  TermsRoute: typeof TermsRoute
  VendorRoute: typeof VendorRouteWithChildren
  WishlistRoute: typeof WishlistRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  VendorsVendorIdRoute: typeof VendorsVendorIdRoute
  VendorsIndexRoute: typeof VendorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/500': {
      id: '/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof R500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addresses': {
      id: '/addresses'
      path: '/addresses'
      fullPath: '/addresses'
      preLoaderRoute: typeof AddressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-delivery': {
      id: '/become-delivery'
      path: '/become-delivery'
      fullPath: '/become-delivery'
      preLoaderRoute: typeof BecomeDeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-vendor': {
      id: '/become-vendor'
      path: '/become-vendor'
      fullPath: '/become-vendor'
      preLoaderRoute: typeof BecomeVendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-success': {
      id: '/order-success'
      path: '/order-success'
      fullPath: '/order-success'
      preLoaderRoute: typeof OrderSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/street-vendors': {
      id: '/street-vendors'
      path: '/street-vendors'
      fullPath: '/street-vendors'
      preLoaderRoute: typeof StreetVendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor': {
      id: '/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof VendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery/login': {
      id: '/delivery/login'
      path: '/login'
      fullPath: '/delivery/login'
      preLoaderRoute: typeof DeliveryLoginRouteImport
      parentRoute: typeof DeliveryRoute
    }
    '/orders/track': {
      id: '/orders/track'
      path: '/track'
      fullPath: '/orders/track'
      preLoaderRoute: typeof OrdersTrackRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/login': {
      id: '/vendor/login'
      path: '/login'
      fullPath: '/vendor/login'
      preLoaderRoute: typeof VendorLoginRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/roaming': {
      id: '/vendor/roaming'
      path: '/roaming'
      fullPath: '/vendor/roaming'
      preLoaderRoute: typeof VendorRoamingRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendors/': {
      id: '/vendors/'
      path: '/vendors'
      fullPath: '/vendors/'
      preLoaderRoute: typeof VendorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/$vendorId': {
      id: '/vendors/$vendorId'
      path: '/vendors/$vendorId'
      fullPath: '/vendors/$vendorId'
      preLoaderRoute: typeof VendorsVendorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId/track': {
      id: '/orders/$orderId/track'
      path: '/$orderId/track'
      fullPath: '/orders/$orderId/track'
      preLoaderRoute: typeof OrdersOrderIdTrackRouteImport
      parentRoute: typeof OrdersRoute
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DeliveryRouteChildren {
  DeliveryLoginRoute: typeof DeliveryLoginRoute
}

const DeliveryRouteChildren: DeliveryRouteChildren = {
  DeliveryLoginRoute: DeliveryLoginRoute,
}

const DeliveryRouteWithChildren = DeliveryRoute._addFileChildren(
  DeliveryRouteChildren,
)

interface OrdersRouteChildren {
  OrdersTrackRoute: typeof OrdersTrackRoute
  OrdersOrderIdTrackRoute: typeof OrdersOrderIdTrackRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersTrackRoute: OrdersTrackRoute,
  OrdersOrderIdTrackRoute: OrdersOrderIdTrackRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

interface VendorRouteChildren {
  VendorLoginRoute: typeof VendorLoginRoute
  VendorRoamingRoute: typeof VendorRoamingRoute
}

const VendorRouteChildren: VendorRouteChildren = {
  VendorLoginRoute: VendorLoginRoute,
  VendorRoamingRoute: VendorRoamingRoute,
}

const VendorRouteWithChildren =
  VendorRoute._addFileChildren(VendorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R500Route: R500Route,
  AboutRoute: AboutRoute,
  AddressesRoute: AddressesRoute,
  AdminRoute: AdminRouteWithChildren,
  BecomeDeliveryRoute: BecomeDeliveryRoute,
  BecomeVendorRoute: BecomeVendorRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  DeliveryRoute: DeliveryRouteWithChildren,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  OfflineRoute: OfflineRoute,
  OrderSuccessRoute: OrderSuccessRoute,
  OrdersRoute: OrdersRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SignupRoute: SignupRoute,
  StreetVendorsRoute: StreetVendorsRoute,
  TermsRoute: TermsRoute,
  VendorRoute: VendorRouteWithChildren,
  WishlistRoute: WishlistRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  VendorsVendorIdRoute: VendorsVendorIdRoute,
  VendorsIndexRoute: VendorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
