export const BCRYPT_SALT_ROUNDS = 12;

export const ACCESS_TOKEN_TYPE = "access";
export const REFRESH_TOKEN_TYPE = "refresh";

export const REFRESH_TOKEN_BYTES = 48;
export const REFRESH_TOKEN_HEX_LENGTH = REFRESH_TOKEN_BYTES * 2;

export const EMAIL_VERIFY_TOKEN_BYTES = 32;

export const PASSWORD_RULES = {
  MIN_LENGTH: 8,
  MAX_LENGTH: 72, // bcrypt truncates after 72 bytes
  REQUIRE_UPPERCASE: true,
  REQUIRE_LOWERCASE: true,
  REQUIRE_NUMBER: true,
  REQUIRE_SPECIAL: true,
} as const;

export const AUDIT_ACTIONS = {
  USER_REGISTERED: "user.registered",
  USER_LOGIN_SUCCESS: "user.login.success",
  USER_LOGIN_FAILED: "user.login.failed",
  USER_LOGIN_GOOGLE: "user.login.google",
  USER_LOGIN_OTP_SENT: "user.login.otp_sent",
  USER_LOGIN_OTP_VERIFIED: "user.login.otp_verified",
  USER_LOGOUT: "user.logout",
  USER_LOGOUT_ALL: "user.logout_all",
  REFRESH_TOKEN_USED: "auth.refresh",
  REFRESH_TOKEN_REVOKED: "auth.refresh.revoked",
  EMAIL_VERIFIED: "user.email_verified",
  EMAIL_VERIFICATION_SENT: "user.email_verification_sent",
  PASSWORD_RESET_REQUESTED: "user.password_reset_requested",
  PASSWORD_RESET: "user.password_reset",
  PASSWORD_CHANGED: "user.password_changed",
  OTP_SENT: "user.otp_sent",
  PROFILE_UPDATED: "user.profile_updated",
  USER_DEACTIVATED: "user.deactivated",
  GUEST_LOGIN: "user.guest_login",
  CATEGORY_CREATED: "category.created",
  CATEGORY_UPDATED: "category.updated",
  CATEGORY_DELETED: "category.deleted",
  VENDOR_REGISTERED: "vendor.registered",
  VENDOR_UPDATED: "vendor.updated",
  VENDOR_APPROVED: "vendor.approved",
  VENDOR_REJECTED: "vendor.rejected",
  VENDOR_SUSPENDED: "vendor.suspended",
  VENDOR_STATUS_TOGGLED: "vendor.status_toggled",
  VENDOR_LOCATION_UPDATED: "vendor.location_updated",
  VENDOR_DELETED: "vendor.deleted",
  PRODUCT_CREATED: "product.created",
  PRODUCT_UPDATED: "product.updated",
  PRODUCT_DELETED: "product.deleted",
  REVIEW_CREATED: "review.created",
  INVENTORY_UPDATED: "inventory.updated",
  IMAGE_ADDED: "image.added",
  IMAGE_REMOVED: "image.removed",
  FILE_UPLOADED: "file.uploaded",
  FILE_DELETED: "file.deleted",
  CART_ITEM_ADDED: "cart.item_added",
  CART_ITEM_UPDATED: "cart.item_updated",
  CART_ITEM_REMOVED: "cart.item_removed",
  CART_CLEARED: "cart.cleared",
  WISHLIST_ITEM_ADDED: "wishlist.item_added",
  WISHLIST_ITEM_REMOVED: "wishlist.item_removed",
  COUPON_CREATED: "coupon.created",
  COUPON_UPDATED: "coupon.updated",
  COUPON_DELETED: "coupon.deleted",
  CHECKOUT_PREVIEWED: "checkout.previewed",
  ORDER_PLACED: "order.placed",
  ORDER_CANCELLED: "order.cancelled",
  ORDER_STATUS_CHANGED: "order.status_changed",
  ORDER_REFUNDED: "order.refunded",
  PAYMENT_INITIATED: "payment.initiated",
  PAYMENT_VERIFIED: "payment.verified",
  PAYMENT_REFUNDED: "payment.refunded",
  USER_SUSPENDED: "user.suspended",
  USER_ACTIVATED: "user.activated",
  USER_RESTORED: "user.restored",
  USER_ROLE_CHANGED: "user.role_changed",
  USER_PASSWORD_RESET_BY_ADMIN: "user.password_reset_by_admin",
  USER_FORCE_LOGGED_OUT: "user.force_logged_out",
  VENDOR_RESTORED: "vendor.restored",
  DELIVERY_CREATED: "delivery.created",
  DELIVERY_APPROVED: "delivery.approved",
  DELIVERY_REJECTED: "delivery.rejected",
  DELIVERY_SUSPENDED: "delivery.suspended",
  DELIVERY_RESTORED: "delivery.restored",
  SETTINGS_UPDATED: "settings.updated",
  ANNOUNCEMENT_CREATED: "announcement.created",
  ANNOUNCEMENT_UPDATED: "announcement.updated",
  ANNOUNCEMENT_DELETED: "announcement.deleted",
  ANNOUNCEMENT_PUBLISHED: "announcement.published",
  ANNOUNCEMENT_UNPUBLISHED: "announcement.unpublished",
  REPORT_EXPORTED: "report.exported",
  KYC_SUBMITTED: "kyc.submitted",
  DELIVERY_REGISTERED: "delivery.registered",
  DELIVERY_ACCEPTED: "delivery.accepted",
  GALI_BELL_RUNG: "gali_bell.rung",
  ORDER_RETURNED: "order.returned",
} as const;
