export const ROLES = {
  CUSTOMER: "customer",
  VENDOR: "vendor",
  DELIVERY_PARTNER: "delivery",
  ADMIN: "admin",
  SUPER_ADMIN: "super_admin",
} as const;

export type RoleSlug = (typeof ROLES)[keyof typeof ROLES];

export const PERMISSIONS = {
  // Auth
  AUTH_SELF: "auth:self",

  // Users
  USERS_READ: "users:read",
  USERS_UPDATE: "users:update",
  USERS_DELETE: "users:delete",
  USERS_MANAGE: "users:manage",

  // Products
  PRODUCTS_READ: "products:read",
  PRODUCTS_CREATE: "products:create",
  PRODUCTS_UPDATE: "products:update",
  PRODUCTS_DELETE: "products:delete",
  PRODUCTS_FEATURE: "products:feature",
  PRODUCTS_APPROVE: "products:approve",

  // Vendors
  VENDORS_READ: "vendors:read",
  VENDORS_CREATE: "vendors:create",
  VENDORS_UPDATE: "vendors:update",
  VENDORS_DELETE: "vendors:delete",
  VENDORS_APPROVE: "vendors:approve",

  // Delivery
  DELIVERY_READ: "delivery:read",
  DELIVERY_CREATE: "delivery:create",
  DELIVERY_UPDATE: "delivery:update",
  DELIVERY_APPROVE: "delivery:approve",

  // Orders
  ORDERS_READ: "orders:read",
  ORDERS_CREATE: "orders:create",
  ORDERS_UPDATE: "orders:update",
  ORDERS_CANCEL: "orders:cancel",
  ORDERS_REFUND: "orders:refund",

  // Payments
  PAYMENTS_READ: "payments:read",
  PAYMENTS_REFUND: "payments:refund",
  PAYMENTS_VERIFY: "payments:verify",

  // Categories
  CATEGORIES_READ: "categories:read",
  CATEGORIES_CREATE: "categories:create",
  CATEGORIES_UPDATE: "categories:update",
  CATEGORIES_DELETE: "categories:delete",

  // Coupons
  COUPONS_READ: "coupons:read",
  COUPONS_CREATE: "coupons:create",
  COUPONS_UPDATE: "coupons:update",
  COUPONS_DELETE: "coupons:delete",

  // Reviews
  REVIEWS_CREATE: "reviews:create",
  REVIEWS_MODERATE: "reviews:moderate",

  // Notifications
  NOTIFICATIONS_READ: "notifications:read",
  NOTIFICATIONS_SEND: "notifications:send",

  // Admin / Platform
  DASHBOARD_READ: "dashboard:read",
  SETTINGS_READ: "settings:read",
  SETTINGS_MANAGE: "settings:manage",
  AUDIT_LOGS_READ: "audit:read",
  REPORTS_READ: "reports:read",
  USERS_IMPERSONATE: "users:impersonate",
  CMS_MANAGE: "cms:manage",

  // Broadcasts
  BROADCASTS_READ: "broadcasts:read",
  BROADCASTS_CREATE: "broadcasts:create",
  BROADCASTS_DELETE: "broadcasts:delete",
} as const;

export type PermissionSlug = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ADMIN_PERMISSIONS: PermissionSlug[] = [
  PERMISSIONS.AUTH_SELF,
  PERMISSIONS.USERS_READ,
  PERMISSIONS.USERS_UPDATE,
  PERMISSIONS.USERS_MANAGE,
  PERMISSIONS.PRODUCTS_READ,
  PERMISSIONS.PRODUCTS_CREATE,
  PERMISSIONS.PRODUCTS_UPDATE,
  PERMISSIONS.PRODUCTS_DELETE,
  PERMISSIONS.PRODUCTS_FEATURE,
  PERMISSIONS.PRODUCTS_APPROVE,
  PERMISSIONS.VENDORS_READ,
  PERMISSIONS.VENDORS_UPDATE,
  PERMISSIONS.VENDORS_DELETE,
  PERMISSIONS.VENDORS_APPROVE,
  PERMISSIONS.DELIVERY_READ,
  PERMISSIONS.DELIVERY_UPDATE,
  PERMISSIONS.DELIVERY_APPROVE,
  PERMISSIONS.ORDERS_READ,
  PERMISSIONS.ORDERS_UPDATE,
  PERMISSIONS.ORDERS_REFUND,
  PERMISSIONS.PAYMENTS_READ,
  PERMISSIONS.PAYMENTS_REFUND,
  PERMISSIONS.PAYMENTS_VERIFY,
  PERMISSIONS.CATEGORIES_READ,
  PERMISSIONS.CATEGORIES_CREATE,
  PERMISSIONS.CATEGORIES_UPDATE,
  PERMISSIONS.CATEGORIES_DELETE,
  PERMISSIONS.COUPONS_READ,
  PERMISSIONS.COUPONS_CREATE,
  PERMISSIONS.COUPONS_UPDATE,
  PERMISSIONS.COUPONS_DELETE,
  PERMISSIONS.REVIEWS_MODERATE,
  PERMISSIONS.NOTIFICATIONS_READ,
  PERMISSIONS.NOTIFICATIONS_SEND,
  PERMISSIONS.DASHBOARD_READ,
  PERMISSIONS.SETTINGS_READ,
  PERMISSIONS.SETTINGS_MANAGE,
  PERMISSIONS.AUDIT_LOGS_READ,
  PERMISSIONS.REPORTS_READ,
  PERMISSIONS.CMS_MANAGE,
  PERMISSIONS.BROADCASTS_READ,
  PERMISSIONS.BROADCASTS_CREATE,
  PERMISSIONS.BROADCASTS_DELETE,
];

export const ROLE_PERMISSIONS: Record<RoleSlug, PermissionSlug[]> = {
  customer: [
    PERMISSIONS.AUTH_SELF,
    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.VENDORS_READ,
    PERMISSIONS.CATEGORIES_READ,
    PERMISSIONS.ORDERS_READ,
    PERMISSIONS.ORDERS_CREATE,
    PERMISSIONS.ORDERS_CANCEL,
    PERMISSIONS.PAYMENTS_READ,
    PERMISSIONS.REVIEWS_CREATE,
    PERMISSIONS.NOTIFICATIONS_READ,
    PERMISSIONS.BROADCASTS_READ,
  ],
  vendor: [
    PERMISSIONS.AUTH_SELF,
    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.PRODUCTS_CREATE,
    PERMISSIONS.PRODUCTS_UPDATE,
    PERMISSIONS.PRODUCTS_DELETE,
    PERMISSIONS.VENDORS_READ,
    PERMISSIONS.VENDORS_UPDATE,
    PERMISSIONS.ORDERS_READ,
    PERMISSIONS.ORDERS_UPDATE,
    PERMISSIONS.CATEGORIES_READ,
    PERMISSIONS.PAYMENTS_READ,
    PERMISSIONS.NOTIFICATIONS_READ,
    PERMISSIONS.BROADCASTS_READ,
    PERMISSIONS.BROADCASTS_CREATE,
    PERMISSIONS.BROADCASTS_DELETE,
  ],
  delivery: [
    PERMISSIONS.AUTH_SELF,
    PERMISSIONS.DELIVERY_UPDATE,
    PERMISSIONS.ORDERS_READ,
    PERMISSIONS.ORDERS_UPDATE,
    PERMISSIONS.PAYMENTS_READ,
    PERMISSIONS.NOTIFICATIONS_READ,
  ],
  admin: ADMIN_PERMISSIONS,
  super_admin: [
    ...ADMIN_PERMISSIONS,
    PERMISSIONS.USERS_DELETE,
    PERMISSIONS.VENDORS_DELETE,
    PERMISSIONS.COUPONS_DELETE,
    PERMISSIONS.USERS_IMPERSONATE,
  ],
};

export const DEFAULT_ROLE_MAP: Record<string, string> = {
  customer: "customer",
  vendor: "vendor",
  delivery: "delivery",
  admin: "admin",
  super_admin: "super_admin",
};
